### ISSUE TITLE
I think there is no need to expose the db

### ISSUE THREAD

**Issue by PhilipMay** [Toumash/mlflow-docker#12]
Hi. Thanks for this nice work.
Just one comment: I think there is no need to expose the database. It is just needed internaly.
See here:

https://github.com/Toumash/mlflow-docker/blob/b6ecfe7d0c0b8c3d3674b1d5a1a63c4d6f6249df/docker-compose.yml#L22

**Comment by Toumash** [comment]
Yes, you're right.

**Comment by Toumash** [comment]
Actually, in newest docker, the "expose" keyword has no impact on the service, its just an information
https://stackoverflow.com/a/40801773/3711660
