### ISSUE TITLE
Wrong bucket name in mc mb command.

### ISSUE THREAD

**Issue by TheoLisin** [Toumash/mlflow-docker#19]
Hi! 

You run the `mlflow` server using the `${AWS_BUCKET_NAME}` variable.

```
entrypoint: bash ./wait-for-it.sh db:3306 -t 90 -- mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root s3://${AWS_BUCKET_NAME}/ --artifacts-destination s3://${AWS_BUCKET_NAME}/ -h 0.0.0.0
```
However, you build a bucket called "mlflow" in the `create_s3_buckets`.

```
/usr/bin/mc mb minio/mlflow;
```

It appears that you meant to type `${AWS_BUCKET_NAME}` in both commands.

I apologise in advance if everything is correct and I simply misinterpreted anything)

**Comment by Toumash** [comment]
Thank you for your contribution!

You're right, i've prepared a PR #20
