### ISSUE TITLE
Add optuna to the mix

### ISSUE THREAD

**Issue by s-celles** [Toumash/mlflow-docker#28]
Hello,

I'm trying to install optuna on top of your install but I'm facing an error - see https://github.com/optuna/optuna/issues/5360

What kind of hyperparameters optimizer are you using ?

Could you add it to the "mix" ?

Kind regards

**Comment by Toumash** [comment]
Out of scope. I've looked into the issue and it looks like a optuna problem with the database.

Unfortunately im not using any optimizer, and im not even a data scientist : D

**Comment by s-celles** [comment]
Thanks @Toumash for prompt answer!
