### ISSUE TITLE
[Need help] Minio Port 9000 is redirecting to http://localhost:32965/ and not able connect.

### ISSUE THREAD

**Issue by TheSunilVarma** [Toumash/mlflow-docker#6]
My SETUP
I'm trying to use this as mlflow starter project and i'm configuring it in WSL2 (Ubuntu 20.04 LTS) and docker with WSL2.
NOTE : I have working mlflow with this setup, but not minio !

[container] aws-s3 
LOG :
WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.

Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD

API: http://172.19.0.4:9000 http://127.0.0.1:9000

Console: http://172.19.0.4:32965 http://127.0.0.1:32965

Documentation: https://docs.min.io

WARNING: Console endpoint is listening on a dynamic port (32965), please use --console-address ":PORT" to choose a static port.

**Comment by TheSunilVarma** [comment]
UPDATE : I have tried this ( updating port to 9001 instead 9000 but no luck as suggested somewhere in minio issue ) : https://stackoverflow.com/questions/65546108/where-is-hostconfig-json-docker-desktop-wsl2-environment

**Comment by Toumash** [comment]
Thanks for informing me! Minio released a [feature update 11 days ago](https://github.com/minio/minio/releases/tag/RELEASE.2021-07-08T01-15-01Z) and they separated the GUI (console) and API port so thats why its not working right now.
Im gonna set the version to point to the latest stable one for now, but a Pull Request which will provide the console port is welcome :)

The PR should do something like this 
```
podman run \
  -p 9000:9000 \
  -p 9001:9001 \
  minio/minio server /data --console-address ":9001"
```
Im unsure how to hass the --console-address in the docker compose format at this moment, but if you know you can create a pull request ;)

**Comment by Toumash** [comment]
For know let me know if [this PR fixes the issue](https://github.com/Toumash/mlflow-docker/pull/7).
Just change the `docer-compose.yml`file:
from
`image: minio/minio:latest` 
to
 `image: minio/minio:RELEASE.2021-06-14T01-29-23Z`

**Comment by Toumash** [comment]
Waiting for the feedback

**Comment by TheSunilVarma** [comment]
Yeepppii it worked !!!!!... 
And
Thanks for your quick response.

**Comment by sosnus** [comment]
Same problem, ` --console-address ":9001"` is important. What is difference between run images without, and with this parameter?
WITHOUT:
```
Status:         1 Online, 0 Offline. 
S3-API: http://172.17.0.2:9000  http://127.0.0.1:9000 
Console: http://172.17.0.2:35031 http://127.0.0.1:35031 
```

WITH:
```
Status:         1 Online, 0 Offline. 
S3-API: http://172.17.0.2:9000  http://127.0.0.1:9000 
Console: http://172.17.0.2:9001 http://127.0.0.1:9001
```

When I run without flag ` --console-address ":9001"`, I'm redirected from 9000 to 35031 , but it not working. After add this command, I do not see redirection. Thank You all!
